spring:
  jmx:
    enabled: false

server:
  shutdown: graceful

management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

